dns_domain: "ENC[AES256_GCM,data:ao22D1gbwQELwY0=,iv:hG69TbLfq6KGGO9oLpp+5/37AJ8C/AFKQWz1g9iofgE=,tag:L1pK5ncgcRYXTAGf7qDQxg==,type:str]"
dns_desec_rrsets:
  - subname: "ENC[AES256_GCM,data:+QaAQV9D6g==,iv:/AYaLzv8AGmWRFqxDFJaCL55uZ8PWuHXhP+CQ9Oipao=,tag:MfBucy5yM8iJjMhtDt0XGA==,type:str]"
    type: "ENC[AES256_GCM,data:FNoB5Q==,iv:4N421Bx11Llk4OZ7+zdLrRLgVyASdL4qPt6cdD30JxY=,tag:X5nxo6nIuTPpwcpEIgTlBw==,type:str]"
    ttl: "ENC[AES256_GCM,data:jEBhpg==,iv:P9dsmTcbFi02tLKSzZFYh4ufGljjzOZS+zrlUZgo1SQ=,tag:T70qz1LwpbogrNtTnM/chg==,type:int]"
    records:
      - "ENC[AES256_GCM,data:SVtQ/FhWhSisEV4z2unlJ7A+SZnHLX47qQAtAaWYwRfQSAI=,iv:GYarv/cmrQRwRLhgQYYKZ3n5R6J2iVP3nHxPhKM2VfA=,tag:kjdX2n09kJ8LlQ3yYwHNkw==,type:str]"
  - subname: "ENC[AES256_GCM,data:Ek1BlSAnSQ==,iv:IJRhBGd+HoxKS07H+ypmlBAdehmGvLltrpitynZ/0I0=,tag:3pYV2BNTQExO22wB6eB0eg==,type:str]"
    type: "ENC[AES256_GCM,data:wQ==,iv:CwNyjyZLS9DQBBQsN3wFRULnPwHH5NcZcmWAxZMhU2c=,tag:b8H90Ms/7PguXkUWncxzSA==,type:str]"
    ttl: "ENC[AES256_GCM,data:nMwtbQ==,iv:QwC332EOlp/LVdjwCtFPdQ0uwA9Qnjvprk94k9Fol8k=,tag:DT7ZcV2AcheeAcisN8W/Qw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:GjGmAbCmsq7Q2q7jFg==,iv:7lOQqeOClLlsTwjYEBogPjCK9lRtt/NqzfXFdspNtTM=,tag:mpv3Ef6N66vp3VgK/bkong==,type:str]"
  - subname: "ENC[AES256_GCM,data:fq95KvP3+w==,iv:HHTgpjBWRRWM+Qxa3VkiQwA5D5aw3ErfE+2CDbOlw+w=,tag:viBTZxP1QUX9qJn7h4MWIw==,type:str]"
    type: "ENC[AES256_GCM,data:wEz9,iv:OKnPJWizsNmexIFI0aoRes4yqjuFLcU9Ia/K911Lbtk=,tag:RN0d7hIDrHvokpzQ4eE29g==,type:str]"
    ttl: "ENC[AES256_GCM,data:aju0gQ==,iv:X4iH3F6C7pGvdhFgskWABL4FA+mFZ8o7G/j02EznToQ=,tag:E3LzB/PM1sZmSnOmmCW65Q==,type:int]"
    records:
      - "ENC[AES256_GCM,data:zcNcSZYLEGCSsXEwW8XMU4Ef1Hm3Vi8DB/HnlVjLJFLF5auVmiyXIJA0MaoPDLA1Aq9Wu2mLjh5vtZjMOquo7+RlK4vwv7v/z22z0UFhdloVeqkfSMWtaI4qAaECjjLfap/pc52ZLMd+V+goRvjSq+VnGzFBE/GDhADZ,iv:PNWAkOaqG3Sh3102olvXdibw7/iw42HzcSvOSrPZts4=,tag:c1l4TsaRQjpOhUaTOxfMug==,type:str]"
  - subname: "ENC[AES256_GCM,data:zpJmE9aD28ASrLFILuJJJF6l7/19Zw==,iv:LC8pgoeD2Kxcqfqap40PWiuNIt4nzwcByvcUHH1sDkE=,tag:lj/sQZaoxJB0WaNEzJMr0w==,type:str]"
    type: "ENC[AES256_GCM,data:+34290o=,iv:rBHF3SKN4EL9eEWP1dUxdOdOKoKm/NrzhRvYWj3HB6w=,tag:TEWAU3OvGAh48v9/OUnRKw==,type:str]"
    ttl: "ENC[AES256_GCM,data:PmAFHw==,iv:742DU9+H/06Z2/ZDH02UyRsxGIFc3NSvH7fTmgFTJG0=,tag:IARXXlVKijugWiZ3PPiscQ==,type:int]"
    records:
      - "ENC[AES256_GCM,data:Ix6oiDf/HLeKVYlr43nnnHgdg//7w9xY07BYeiK42Nis4R3u/c3y1XCArmUBTqHvA9ynG0Xk5OvJ4owf7SlsohgK9j6qXz+ubf6IPg4VriogXjt9dxXN/DbEv6OHyQ==,iv:CtnrktoJ75kwODnxPC+IarAsDIAWdBj9h1vjZr8YMHQ=,tag:T3XaFd/JRTTAi6ow/1yESw==,type:str]"
  - subname: "ENC[AES256_GCM,data:aS2Q9Xs8KKDSEsQn28KqgSQw1U8I0w==,iv:73acC6EnjBAe9r+v6MmwvrP0LebBBLIm7VCKUzGl7Fg=,tag:b+gV4Uuf37Rvws03AX+8UA==,type:str]"
    type: "ENC[AES256_GCM,data:ivI8Rro=,iv:Gsy9BjIQk6edwR0Ao7X7k0OGGGOGS8hB++byVCFssUI=,tag:GtSAAMeSbH2PMgzZmRtW0g==,type:str]"
    ttl: "ENC[AES256_GCM,data:wKRYRg==,iv:Z8bel0BSd1C4EI0dRrS+IAOEOE7wbW7WDVzNhDLugI8=,tag:cgfTQsyO3FfUPbvYRje9GA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:fcwb6s3EH8o/fklUCR07Tl+w7yUOG58zJaJ5PAAT8i0Rdh8Jn1stI6sx6m5jfUd1H5SmK17Pgjs6rf6JL8606R8/1oHMYinT+TOg69Lplkviw12fDADvRzUp1w6Dkw==,iv:tV+caG2asdBf9dJZNG5xji8xvU7AShSd/YV0iyOu2QY=,tag:rFsVcCfbFB9ebtBGt506eA==,type:str]"
  - subname: "ENC[AES256_GCM,data:1MCpRjSoth8kyZ0W54MMQfoMDjDA,iv:0UKYhWcJBN1s871WZloNPCOJitJ59uwPvjcwJDMr2/0=,tag:Vra2jDG00UixH6HUfal2Tg==,type:str]"
    type: "ENC[AES256_GCM,data:LKSOEZ0=,iv:pvnSYQ2hZjtkkhL0o+ou0IARMalALeoTtp+IcgfUnuc=,tag:7hp/WeVORX8aaxn8ViMwlg==,type:str]"
    ttl: "ENC[AES256_GCM,data:VARnnA==,iv:35PYyKpCmCwY6cuJlFlcuT/1lGo1KjrySU2vjCxhQJM=,tag:j0/3Tyu8S9UXxLzi+I3qMA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:DN7WqwB5HUPPqnuISm3zBJqGDZhI3ho0FBLG41RGMA8UtIArReNMKNrKYzEG6dyO2YexRkwnKcg5zDQew+w95W3WMRgR6vikg0eD/5daWrsGX9IoXxKv8Lqw5iID,iv:mph2IyCAiMgJnYbglrKSVL2wYccamh02QSsk5S5pgCQ=,tag:kyHJIAIuD88UvmoGJXWSZA==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:F/ln,iv:oGWY/y4TclzVdU4634yQZ3pI7fd1ZuuO34bF3efet90=,tag:/X+F6Wem0rLdMHsQDMJKfg==,type:str]"
    ttl: "ENC[AES256_GCM,data:IvJ9bQ==,iv:1HVJeXH0025sZngw1BvbN63KXjzbDtomDfYeiEcKq6Q=,tag:ze1OixiILMTkiRBdd09TOA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:Q4Bo2EW79c+smbJu7YFoF6k5BCJ6iyiWCg==,iv:w23tpbLq8dtv+5VWAjsjO+lEL7v8mZR12PNoY/J6b98=,tag:7sx/VrWKVgmwEUudDcXRnw==,type:str]"
      - "ENC[AES256_GCM,data:NkmWrp7IVu91llATEU1IPbZ9GzjvIfxGC82E8TlfSFi7jmFADqbFct3zA0c=,iv:06iiyRJFlnNJkdetPflM0MBdmfXgqi4IW4Zm9kC+TJY=,tag:welo9lXWSxQ9p1LiJiNyhg==,type:str]"
      - "ENC[AES256_GCM,data:647hJobhvZIFX+6AZGB/UUk=,iv:s5bHCbzh+zsAApq+SfTRzBde65dWVBb9ZCR2WkZetJ0=,tag:F8CPpvq/+tNYHdUAyAy9Vg==,type:str]"
      - "ENC[AES256_GCM,data:DG/C55mQHAX4QEvusK8iAmjuZJeS15axgQWyYvo=,iv:an04GJpZ6AWfhK4ipx74Zd3FXUXSX40fwlZjPLXQJy0=,tag:SWiOIUlOWMtOjP16gWpJ/A==,type:str]"
      - "ENC[AES256_GCM,data:W9qKuo2SUFmabbLLklMXgt4wbgX61EaVit042a6vlre1qcqVO9NiY65hY/5Ec6zv,iv:BZIZWAmyFB6+PJsTGsVuOSqwCywjU+k2UHFcKDbuGtE=,tag:7YmoeosH7rtM1XPitUXO6w==,type:str]"
      - "ENC[AES256_GCM,data:nLiP6NrkLjX8viMQAAA4a1wO993n,iv:AikNVgi69cUfH21ngJgHha/b/t86cGhT6U64xd1XqKA=,tag:2zCx5jWtUkmnmpZorMEYdA==,type:str]"
      - "ENC[AES256_GCM,data:W2G6A8igjuxxzHjhc3WOEw==,iv:SHITfJLtprK4GGEjEFqzwDrQcgxKzk4zqMBv32wN8Qs=,tag:y5XRyB8Tts+fWupMIPA9yw==,type:str]"
      - "ENC[AES256_GCM,data:IpooVuzm1QGcPwGwxd6xkdg=,iv:CdqNazvpY8UDUjFNPJ09FAIHntsI3yMv0J2Dky0Z5FE=,tag:WEDVW9/GXUwJPzTzpQqNoA==,type:str]"
      - "ENC[AES256_GCM,data:fai5SO8sFjWvciGTQiNg+7a4+krfChNMMn3Qi+83cVCnxw==,iv:tDBKcnGUu7MMBv5ii2JCyoJfH90QvfRKS3EYYz1kYGw=,tag:XN1TfepYOL8c4cRbYFwbDg==,type:str]"
  - subname: "ENC[AES256_GCM,data:Kf5tx2tEP/YIOA==,iv:RUYeSIP82UzaSraMima6v2nywuZHpzwG1jh7i5XsXgg=,tag:ECI+TCOzH62/GtTS8oYjrg==,type:str]"
    type: "ENC[AES256_GCM,data:oFKM,iv:Fe42on7o2hzvdzUsAOLcyvLEQUiLkUuMN42YoDcJ7hA=,tag:94HzoIlXmJoEQVsdQqAPPw==,type:str]"
    ttl: "ENC[AES256_GCM,data:mD4e/g==,iv:a1A5xcc7UkEO9VbGpOiaAfwVYE9eb9ZBw3p0cjxjYPw=,tag:RDfqtWZ9b9qVL7Mg5VwjMw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:tiJ1c3oFvXF+qs8U46qA9HCWf6JIMBmByYeUvdXQaJ9NOq0Ve9drBniWAuo=,iv:QnvshYc8a6OGnrdJ/sol/At8Gc2Ol0nLRIScw9hhVtU=,tag:cOcq0INB6TUn1ZUxWbX1hQ==,type:str]"
  - subname: "ENC[AES256_GCM,data:LYqlL1LdEQ==,iv:dkN3ZUQxhIu7H1QLE30uS7aYZi7kCIr1+avIHZl0/bQ=,tag:ef6bNsivAAMNd5FiTXaUVQ==,type:str]"
    type: "ENC[AES256_GCM,data:tw4tr54=,iv:It6r5T9poSZu/9n/SicPDVpJdeKAErkSTGmlypBgkrM=,tag:G2jphnxtut99lFkYuu2pnw==,type:str]"
    ttl: "ENC[AES256_GCM,data:GWaluA==,iv:DROfNP/6d4cQ1nh/fIVJFWdMx7QxIY8j1GgE/clJPTg=,tag:np/9QkmAE1ZcRcxwYu3BoA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:sm/gUVsMSrm32jtP3pU1Sr0sZuLBh1LEmTzgzqDUlGgM,iv:J6IR80Tlgjx7EW/YfH9JHhZg0gr0oB7u4FYgv3hyx4U=,tag:+VjyuySfIfCwc3t9wOzpmw==,type:str]"
  - subname: "ENC[AES256_GCM,data:TnfRNsMzAxM=,iv:sC/dN8CCbVZTZLVNdIGzWWl6piiL8lP/mTyGsF8sKSw=,tag:oHJ2hqWZdZJcMWDy0jRzYQ==,type:str]"
    type: "ENC[AES256_GCM,data:b6OO,iv:V8PjqaSwxCFtLIqlLFaNeZOriM5x5z4/QmAqQjLeyHE=,tag:4ZV+2yAF03BbvWrhY2BHQw==,type:str]"
    ttl: "ENC[AES256_GCM,data:aRETcQ==,iv:XbQZU9KPtHSVIrMhqDIjjfHkXRdNg1hJ/xinZi1cDkM=,tag:X+xHyyanwxvXEJhstX/oCA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:5O9lhYzAFZHJC+fsWjECTEiZMEp51X6S,iv:MGGeZrbF5oZGMDlezU7FXUjG4xUyTMGvgum/tJ6lNtw=,tag:8DOTSHFK71LUpklgtnu1Lg==,type:str]"
  - subname: "ENC[AES256_GCM,data:F8JhJaHl,iv:S5Vi/K5kI0KAdlfv7Itqmfm5GHHb5VdzsIbjZQOx8EI=,tag:w+GLwfFlJi3bS9mweoRnnA==,type:str]"
    type: "ENC[AES256_GCM,data:Kvbr,iv:VD5dMyB5B1WhK1uhAOoWqqXsRxPImoGNA9D9qCzsZzI=,tag:ueVwket+iOxyMkD0jB7djg==,type:str]"
    ttl: "ENC[AES256_GCM,data:nenADw==,iv:uzK+ta13xC8dqlry/BYLtAN+VQQuzTka2c5xY5WqGqw=,tag:jnAjnnpwcontHoj1z3NPiw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:uhHAjFk6EDyfb0/KEMoo5YKNg2exr0+HKJSAYGCH8Uf6H+QgXs3qYIaLwx/nPrUdFT7g6Jnq1LKqnZ+69ptahbphI8g1xL1zX2/tQ1vXbeetlR6OIvtGbIzLrTcR3+tZJb/QKPK6TA==,iv:TrUtd6aZ0+AtepCXBqwJZNP6xWfcO1yIHS5ma34m0q4=,tag:0BbYuLZQz3K/Ct0M7vrcRg==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:dt4i,iv:UWPx2jzANmAzsA4v+OlGEs/s7T/Vm9Vpea3ond9ftPI=,tag:bBGuHXpYOOq/7xPZo9fuHA==,type:str]"
    ttl: "ENC[AES256_GCM,data:+miaGQ==,iv:ncvjpsBLkYLkIQZgkYVw7yx7y5l7EpO+O96RMEO6+dQ=,tag:ccZudUMHFNOLbFwJzT1bHg==,type:int]"
    records:
      - "ENC[AES256_GCM,data:LRKvIzr6XG9R4HBawZQ5xJ94YuISIrh8sROdlbgtfLMrOr5zf/aPZQ==,iv:nVtPOEmqgtjOKYZOJBQExpLkjBUSELE7q1xp/0kyAOg=,tag:B0gwFod5P7EQftBqARJmXw==,type:str]"
      - "ENC[AES256_GCM,data:rPGsjTgc+pSPggv9ro0popaW88I/hpNZexqTP1Pk21RKoPyZwZM5AL3oIAyTnWdhiyJd4SLbA6Zy58gKFmBQ+DT+,iv:6ZVM8mjQMaNXmgVttUVTgEoWTSxWPmlBkG98vYbHvoQ=,tag:eIZkC2a777v7DEtLKvMBlg==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:r2k=,iv:lZNULV9yFmsR2C4NZ1N6sOlV1yfCxof6UGVN2YP10yM=,tag:aPKmq4QUviV4utbSfPPRBQ==,type:str]"
    ttl: "ENC[AES256_GCM,data:QyLpbA==,iv:1Hnxggagl3oLlzllrBa249K7B5a1OqUMG9ZiWukzyt8=,tag:0tebg4+RPdxCRp7Kcv8eZg==,type:int]"
    records:
      - "ENC[AES256_GCM,data:FSQudYkqS+ZTnlQ9BMsC7J4aGddPJjJKtQ==,iv:hP1HSaXgbMdaHfN1xfT3yP/GmoPecWqmP1lIZ/I5nx8=,tag:NsYg5rycFdGiB1vXsHyaUg==,type:str]"
      - "ENC[AES256_GCM,data:/p599PYIdCAdWaDgw42+FU06PCwNkQ==,iv:qFOdwWJmatKApKa4+d5Pu3bjdZL46WrWpPcDKcHJJbE=,tag:RY9aHYEC6Fy5rQloTErONQ==,type:str]"
sops:
  age:
    - enc: "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMRFVkdlNCVDFZdHQyaXNP\nL3FBYzhSL3Q5TmVYdUxnVHFxWWpuRWVkNlI4Cnlkc0E4MlFLTVRCS1BQSmhuRE1s\naXdvbFQranc3LzZQbmorbGtSdEJoK0UKLS0tIHIySHhVdFptNktvT2plZkRHWktD\ncm9PSUU1VXdRTitnVzRjaWxPL1FBRFUKnasEYCrRSwRe8suOXRRPshlyxfnJjzwf\nrX3DdlGG7LVqFH5ltlba/cbNAJT8TfCykRJlIbTjptqYETQKgjzI1g==\n-----END AGE ENCRYPTED FILE-----\n"
      recipient: "age17ggrc2pg965fvc03gfrvag95esywp9ww0tgkygpt70hf206xag5qtcwvwv"
  lastmodified: "2026-06-13T10:48:52Z"
  mac: "ENC[AES256_GCM,data:O4sR3SNxGt/jbwdU+bkKHIRuhwV8PNpzndhcNz7pvMqVh/LicTzgO6VYmOALDCmHgWCIs5t7KutbYneqHAC5qt3UZ2KHAVYG9jOZSmXxB7c/yFj9eBT6XWUpgQvW0HXayy+HEVHykIKm592tmKbPWAHVA8R6yLMki8C8gyhnqc4=,iv:4O08R0LFnP1PMlESroDu1zMJncum3Ejissnu5WI2UuQ=,tag:IIIRn4orVZIYyH5ygVhNLA==,type:str]"
  unencrypted_suffix: "_unencrypted"
  version: "3.13.1"
