---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    cooldown:
      default-days: 7
    allow:
      - dependency-name: 'actions/checkout'
      - dependency-name: 'actions/configure-pages'
      - dependency-name: 'actions/upload-pages-artifact'
      - dependency-name: 'actions/deploy-pages'
