---
- name: 'Setup Proxmox Virtual Environment'
  hosts: 'pve'
  become: true
  tasks:
    - name: 'Set hostname to inventory hostname'
      ansible.builtin.hostname:
        name: '{{ inventory_hostname }}'
