---
- name: 'Set SSH unit facts'
  ansible.builtin.set_fact:
    hardening_sshd_service: '{{ hardening_ssh_service_unit | default(''sshd.service'') }}'
    hardening_sshd_socket: '{{ hardening_ssh_socket_unit | default(''sshd.socket'') }}'

- name: 'Create /etc/ssh/sshd_config.d/'
  ansible.builtin.file:
    path: '/etc/ssh/sshd_config.d/'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: 'Copy sshd drop-in configuration file'
  ansible.builtin.copy:
    owner: 'root'
    group: 'root'
    mode: '0644'
    src: 'sshd-custom.conf'
    dest: '/etc/ssh/sshd_config.d/10-custom.conf'
  notify:
    - 'Reload sshd units'

- name: 'Configure sshd service override'
  block:
    - name: 'Create /etc/systemd/system/sshd.service.d/'
      ansible.builtin.file:
        path: '/etc/systemd/system/{{ hardening_sshd_service }}.d/'
        state: 'directory'
        owner: 'root'
        group: 'root'
        mode: '0755'

    - name: 'Copy sshd override'
      ansible.builtin.copy:
        owner: 'root'
        group: 'root'
        mode: '0644'
        src: 'sshd-override.conf'
        dest: '/etc/systemd/system/{{ hardening_sshd_service }}.d/override.conf'
      notify: 'Reload sshd units'

- name: 'Disable SSH service and enable SSH socket'
  ansible.builtin.systemd:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    enabled: '{{ item.enabled }}'
  loop:
    - name: '{{ hardening_sshd_service }}'
      state: 'stopped'
      enabled: false
    - name: '{{ hardening_sshd_socket }}'
      state: 'started'
      enabled: true
