---
all:
  children:
    fcos:
      children:
        mail:
          hosts:
            mail-01:
              ansible_host: "mail.example.com"
              node_key: "01"
              mail_hostname: "mail.example.com"
              mail_backup_enabled: false
      hosts:
        worker-01:
          ansible_host: "worker.example.com"
          node_key: "02"
  vars:
    ansible_user: "thefutureisprivate"
