# Merged from GrapheneOS/infrastructure and Metropolis-nexus/Common-Files
# Source: https://github.com/GrapheneOS/infrastructure/blob/main/etc/chrony.conf
# License: https://github.com/GrapheneOS/infrastructure/blob/main/LICENSE
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/chrony/conf.d/10-custom.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE

# NTS sources
server time.cloudflare.com iburst nts
server ntppool1.time.nl iburst nts
server nts.netnod.se iburst nts
server ptbtime1.ptb.de iburst nts
server time.dfm.dk iburst nts
server time.cifelli.xyz iburst nts

minsources 3
authselectmode require

# Network behavior
dscp 46

# State files
driftfile /var/lib/chrony/drift
dumpdir /var/lib/chrony
ntsdumpdir /var/lib/chrony

# Clock behavior
leapseclist /usr/share/zoneinfo/leap-seconds.list
makestep 1.0 3
rtconutc
rtcsync

# Local control and logging
cmdport 0
noclientlog
