# Merged from secureblue/secureblue and Metropolis-nexus/Common-Files
# Source: https://github.com/secureblue/secureblue/blob/live/files/system/etc/security/limits.d/60-disable-coredump.conf
# License: https://github.com/secureblue/secureblue/blob/live/LICENSE
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/security/limits.d/30-disable-coredump.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE

* hard core 0
* soft core 0
