# Sourced from Metropolis-nexus/Common-Files
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/systemd/coredump.conf.d/disable.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE

[Coredump]
Storage=none