# Sourced from Metropolis-nexus/Common-Files
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/NetworkManager/conf.d/00-macrandomize.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE

[device]
wifi.scan-rand-mac-address=yes

[connection]
wifi.cloned-mac-address=random
ethernet.cloned-mac-address=random
connection.stable-id=${CONNECTION}/${BOOT}
