# Sourced from Metropolis-nexus/Common-Files
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/NetworkManager/conf.d/01-transient-hostname.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE

[main]
hostname-mode=none
