# Sourced from GrapheneOS/infrastructure
# Source: https://github.com/GrapheneOS/infrastructure/blob/main/etc/systemd/system/sshd.service.d/override.conf
# License: https://github.com/GrapheneOS/infrastructure/blob/main/LICENSE

[Service]
LimitNOFILE=8192
ManagedOOMPreference=avoid
