# Merged from GrapheneOS/infrastructure, Metropolis-nexus/Common-Files and secureblue/secureblue
# Source: https://github.com/GrapheneOS/infrastructure/blob/main/etc/ssh/sshd_config
# License: https://github.com/GrapheneOS/infrastructure/blob/main/LICENSE
# Source: https://github.com/Metropolis-nexus/Common-Files/blob/main/etc/ssh/sshd_config.d/10-custom.conf
# License: https://github.com/Metropolis-nexus/Common-Files/blob/main/LICENSE
# Source: https://github.com/secureblue/secureblue/blob/live/files/system/server/etc/ssh/sshd_config.d/30-hardening.conf
# License: https://github.com/secureblue/secureblue/blob/live/LICENSE

# Network behavior
IPQoS cs2 cs0

# Encryption hardening
HostKey /etc/ssh/ssh_host_ed25519_key
HostKeyAlgorithms ssh-ed25519
KexAlgorithms mlkem768x25519-sha256
PubkeyAcceptedKeyTypes ssh-ed25519,sk-ssh-ed25519@openssh.com
Ciphers aes256-gcm@openssh.com
MACs -*

# Authentication hardening
AuthenticationMethods publickey
ChallengeResponseAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no
PasswordAuthentication no
PermitRootLogin no
PermitEmptyPasswords no
KbdInteractiveAuthentication no
KerberosAuthentication no
UsePAM yes
AuthorizedKeysFile .ssh/authorized_keys

# Session hardening
AllowAgentForwarding no
AllowStreamLocalForwarding no
AllowTcpForwarding no
Compression no
DisableForwarding yes
LoginGraceTime 30s
MaxAuthTries 3
MaxSessions 2
MaxStartups 4096
PermitUserEnvironment no
PermitUserRC no
StrictModes yes
UseDNS no
X11Forwarding no

# Use SSH keepalives instead of spoofable TCP keepalives.
TCPKeepAlive no
ClientAliveInterval 60
ClientAliveCountMax 2

# Login output
Banner /etc/issue.net
PrintMotd no
