# Sourced from secureblue/secureblue
# Source: https://github.com/secureblue/secureblue/blob/live/files/system/etc/systemd/system.conf.d/60-disable-coredump.conf
# Source: https://github.com/secureblue/secureblue/blob/live/files/system/etc/systemd/user.conf.d/60-disable-coredump.conf
# License: https://github.com/secureblue/secureblue/blob/live/LICENSE

[Manager]
DumpCore=no
