---
pbs_s3_endpoint_id: 'hetzner-fsn1'
pbs_s3_endpoint: 'fsn1.your-objectstorage.com'
pbs_s3_region: 'fsn1'
pbs_s3_datastore_name: 'backup'
pbs_s3_datastore_bucket: 'REPLACE'
pbs_s3_datastore_cache_path: '/var/lib/pbs'
pbs_s3_datastore_reuse: false
pbs_s3_datastore_overwrite_in_use: false
pbs_s3_datastore_gc_schedule: 'daily'
pbs_s3_datastore_prune_schedule: 'daily'
pbs_s3_datastore_retention: {}
pbs_s3_verify_job_id: 'verify-backup'
pbs_s3_verify_schedule: 'daily'
pbs_s3_verify_ignore_verified: true
