dns_domain: "ENC[AES256_GCM,data:NPAuMAJYvLj3XnI=,iv:dQazN/KPDSM1/PmVL6QJu2xOcdaIf5zNs3topwDLxVA=,tag:2s0fBn2utR+0/rZ7eujfZA==,type:str]"
dns_desec_rrsets:
  - subname: "ENC[AES256_GCM,data:4XDLKwAxD4fM3s8JztbUtsM=,iv:kUFmcfn2+xnCBxJiw08tO+sx4OnAlBeayQwLl5TdW6I=,tag:z7Ewq4FAjQKCE4C/fjDm0Q==,type:str]"
    type: "ENC[AES256_GCM,data:Z9BApL8=,iv:XUK6nMKqnoJJ2g8bBPGZbLhqnT/phuPyqSx2OtgKDmI=,tag:2db3ahWz+oV5pY4gRbj6mg==,type:str]"
    ttl: "ENC[AES256_GCM,data:xD1BXw==,iv:Xh5WEuYcsLMjX9mlevXFClCT6eaKrxudmEJDheAeouo=,tag:vwH4+/fLWE5/TEkHuEvWcA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:zeVK9/gytsKdqbpE40Eno6USypbcCKZWyE2pmc8BylyH,iv:cDjWQf1cNUoI7+VBiiBRuSQLeFOeYinFuzr6028g04o=,tag:vBUGvu09uXzqzZID3M3hPQ==,type:str]"
  - subname: "ENC[AES256_GCM,data:9tAOSNSpSeaqEQgTgfCBwVU=,iv:e/v+d12bhAe0Khbbl08eD4iusxxr5IltnT2gJopHlJs=,tag:8EAE/FPGnkvrCmXSdaV2cQ==,type:str]"
    type: "ENC[AES256_GCM,data:BgxFM68=,iv:wONMxR6cBI8PGiOEN4FhEbDqYc0lA2+L4DYT++seAoM=,tag:8rfPpK4yJ/pa0duSOMDpWA==,type:str]"
    ttl: "ENC[AES256_GCM,data:lJoGDg==,iv:Ur/mIaNEdNPAx5M99JeUx00LzdNeX2BMDEbfP7qPR2U=,tag:I8tt6IZtxotSbPFMZVwlnw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:wfwp8F/4VLHRNADsJMW8SJskPs8VAo/fJ+cLyTlBq+At,iv:c0TZuYr6Qgg8jhboi/VKe1QNGmW3YRPMUnyjM0cEOVs=,tag:z/GeorjAuzDjz/gY0m4qmA==,type:str]"
  - subname: "ENC[AES256_GCM,data:FrKnYGB0eZ3bfxlL5TZU,iv:82gRlNHYMf2KRdheS1qfOkRhgxI8fH1qk/KLbMGDSuw=,tag:D4ZChXFFO0xbk2ZWJygGgg==,type:str]"
    type: "ENC[AES256_GCM,data:zGl3iKg=,iv:8r0597E4PRrtpfbWjv9eUEYfR/+0TW71iqnDzwYwpQs=,tag:zxzqjrQBGkjnaxHr87EOdA==,type:str]"
    ttl: "ENC[AES256_GCM,data:iQogNQ==,iv:CFQgMyLfZNHcXWKPkVo3fMolxTlDbXQ/1bjc70e5cno=,tag:ebSLNRsros2+ubLWcYcIBQ==,type:int]"
    records:
      - "ENC[AES256_GCM,data:t4aiLDBaL+Hhn8oXS7l2uK4YB7ayRCsPjds8pZXZNw==,iv:WEwu1Su72mup8UfTHWbMzTmt/fHV9J+X12f09hnXi9U=,tag:YZyWRKUzysNIn6cbKr/Ezw==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:UTLBHXg=,iv:8cpeoyMUuhhnirjopOR8QSSmZyVDV7oH3xbETeAJVDE=,tag:0uM8PX8ijNHe/y4RrjV4Tw==,type:str]"
    ttl: "ENC[AES256_GCM,data:uDBwDg==,iv:WL8obwRwubtfDbucWeR3I8y61LrSVxDiDKBfmd/12lc=,tag:WHMVf7hV2wP+/8myruPXNw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:LnglYEDa3CjGHKz+07HRNVF2nF3/i9Yx7NpNbsoi4r+JS5Ut9hlA0vsmD8V/SgvYT9EX8fRDKsk4t1SpTBIH6jt2j5o=,iv:7yyuidnC9Q+ItfvtdaQ2syD8OPzneBz6YbCNlovsieY=,tag:OKBEkoM6pEriIVKrsfe/Ng==,type:str]"
  - subname: "ENC[AES256_GCM,data:Wx6UiqoUhCxzLg==,iv:zllOCZadQOwxyAAcrbbeqnyNQPy1Z+ekndUBhaH/rIs=,tag:cftb8eqC7fk4P7gNtqiHkw==,type:str]"
    type: "ENC[AES256_GCM,data:kGfn,iv:EaVzv3pgnwLrSGROLvs3eMAHlJxP5oX6JWZ6hvlUQBQ=,tag:2xko1+rdaCb0uE5DMmpiIA==,type:str]"
    ttl: "ENC[AES256_GCM,data:+c5f5A==,iv:uoI3FQiCKA2E228BH452uQXx5OhGJQ918u0/BnA3KNs=,tag:+YQHd0ElKYuvzu8xecGQEg==,type:int]"
    records:
      - "ENC[AES256_GCM,data:TxHSfg7qcjM0Iwd5Z72afpUyXXhu0HIS5pbxmJu2Jyc84gb0YNhAZxm0aH4=,iv:3S3sjODHx0Tz6VhRldRgj/dJ8Rc8Q7IUdBN1lK82yOo=,tag:PPIch+VuV7bZxa7kYeCHzA==,type:str]"
  - subname: "ENC[AES256_GCM,data:8AsGnIWz4Q==,iv:5SneFjYoA6U3Kx6HLYv8JAKqNoHVeFeU0j2UccoGHyg=,tag:7Kxlp4Otd34bb08KzHbDpQ==,type:str]"
    type: "ENC[AES256_GCM,data:6xVYJQI=,iv:5QxN0dPjfdR/Jo8toJOTbV0n68MrRPcxPdimdErAwYo=,tag:xHvF4aluF6lgn8F5wtyF4w==,type:str]"
    ttl: "ENC[AES256_GCM,data:0wzu0Q==,iv:brXGBU/STBfa9/3b74JULUag1zzGQ52zeqK5T7KeUVQ=,tag:ARpH0jiJJcmrXpJp4a6rnA==,type:int]"
    records:
      - "ENC[AES256_GCM,data:TGwVpTdj7tyaLOq+uY26JWZ5qDdTTtnTGVsNRDsHrUl2Cg==,iv:M5ETmxAcvLqjtbh/2tLXZqNt04/PLGhtT5d2smcSppA=,tag:lla1LBo88cP5NWJALPnAqw==,type:str]"
  - subname: "ENC[AES256_GCM,data:tJlafVyAQNo=,iv:0RtZ7WfoGWPrcSNTbySO2NkMVVY1wJAwaCD1Ix5/WLg=,tag:GWis90vq1inLlA6YXIEufQ==,type:str]"
    type: "ENC[AES256_GCM,data:1jNq,iv:1600pMzTaw8hJYTTcX7sBtLSBMnK1Fq7UrJ4tYUJ8cE=,tag:0aaPGlF8okNKFM2Eud3v6g==,type:str]"
    ttl: "ENC[AES256_GCM,data:wvB7hw==,iv:c93FiLU8rWZY+lN86rAMkZAdNOXLQL0xfm5Nk7TaSmA=,tag:kT53ZlyAaE9Xm9MWPMey3g==,type:int]"
    records:
      - "ENC[AES256_GCM,data:oEyWPgMzGprtkcilROdmVzwilOKKrWmk,iv:6n7ha2r77Prqer/WjrJeYxz39DnvLMICfWeW8m396Co=,tag:4MS+k54xt2EO1eohEc5OZw==,type:str]"
  - subname: "ENC[AES256_GCM,data:TugtGcB7,iv:JSQQ6PbaqbafWlRF6Zpy5wCMIElxEukyTk396JbVx5s=,tag:amt18xEbKuMArlJGARz8Kg==,type:str]"
    type: "ENC[AES256_GCM,data:CE8L,iv:hOTHCkH17WaSLZjukM5E2C+xiB2NeICvml8DP/1yVHU=,tag:8/I4c707AXElhTOKYnG68A==,type:str]"
    ttl: "ENC[AES256_GCM,data:r5Wqqw==,iv:d2DqZbCD2jMes0VC+Wez0jkVi+kUfhREHpqDoRzgAdI=,tag:7V4wUPPDDgVSaM67l26Ujg==,type:int]"
    records:
      - "ENC[AES256_GCM,data:hRptuve7ZeHf2VbGayekuPQqzAtKYbPBaWZGhbhHBGJHj8IyGoFdrX9Aive/9nbIUS3ABOZ4C9v82P4NymSwAH3af7v8UcYNqumKyweCZsyIuh9/Sd6y7+2qhhAjCB8XdoAtMC4uRw==,iv:UGp5bQWqTyG4DyYaQyFsBBCC1/1iYUHk86toZ8m52cI=,tag:KwUHCFu/3p/gF9lQlQYdoQ==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:K4oV,iv:b/YLifwat7K9uk2r8CAFCSu8XS2xD18bM3T6DRtSKrA=,tag:7D2nXyYLR5dXL/u34NMg6w==,type:str]"
    ttl: "ENC[AES256_GCM,data:ahGCSg==,iv:NQwA8TB1ujjUZxXzSIY4E4rmTkO/hj/Mxad4sH2djaA=,tag:Iq3qloFvCAqqRjZqPONOrw==,type:int]"
    records:
      - "ENC[AES256_GCM,data:OhGtx+LrDGEkdXZrswfd1vVrpOyHQ3pcyWQYKnPbmaC94PI2,iv:LBU6ho3Or07SegDf8WRIue4RB3Gdrch38EycH3nvPGU=,tag:pvKfre47niRZUhKsogjhcw==,type:str]"
      - "ENC[AES256_GCM,data:nvjUU0pPzKQhdiWVMiFLSnp3YMYKHsZ4irZQ7xqIIaaqpMoyyDfEfglrr0Tft3d+,iv:ceDttzLlYt4Dwz3vNJAFW1zJNNzsWpnIhTmtCtY/r7w=,tag:CCq3lx67ZkRhnglO5JZYvA==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:7fE=,iv:ZJeHePEG+XPmIfOZUSHGHZO/BS3Rac2qJmLQ0lmW5VY=,tag:/fALQypdFuQFKq3m/AjHOw==,type:str]"
    ttl: "ENC[AES256_GCM,data:aV2OdA==,iv:GUrPhCMEPHPBzZUKBimbHy+ialCmOekhSS9Wm8a4klg=,tag:HaMiUWN0g7Z7eBO0dP9F9w==,type:int]"
    records:
      - "ENC[AES256_GCM,data:x86kxsFHKMcg3YYUZ8531lrVaOT3Sw==,iv:WUq4K+VVpvMmodpRZlCci/05AxeD87j4V/zd8GFRDYM=,tag:WC+cxvbcTGd7501jQhGTwA==,type:str]"
      - "ENC[AES256_GCM,data:nVcD+JykUnuglgQvQxeUNJlHGorG8g==,iv:k4pu2GNlwslKNimjEU1VEzs6+h1DUXAPTmjPHg+CI5k=,tag:sntNdMJaMZAGVWlFYsNBuA==,type:str]"
  - subname: ""
    type: "ENC[AES256_GCM,data:NtK1,iv:jMPWcq7Fvmm62kaafOc0ZZ8O9OjODwbLSIxoR1ovzw4=,tag:HRFtr2PxqyCmKKNkssXcqQ==,type:str]"
    ttl: "ENC[AES256_GCM,data:ri109Q==,iv:OUDUIiGvD+sTtuxjgpruI0YVgkNPotr0zDGqqu0+2Hk=,tag:Isx3pDdxlv/M+j13k6vo6Q==,type:int]"
    records:
      - "ENC[AES256_GCM,data:ix5JXqFYcUHKlowM2ORG+rvXg1dJQsWmdg==,iv:QwpjgDo5Rof49COkSF3HWi00d2Tpca3rOMa/5gJ38gU=,tag:OEv31EDUmRxKPdY32SUv4Q==,type:str]"
      - "ENC[AES256_GCM,data:aZGg+7+pZtPZnDxfHr/kLM8Kexx356mCyU3VGCs17nVjGHBw32H6kA/RoDQ=,iv:CUj55RujkLEHwolcft4AyLKNFNRKhAmEu78kbE7exlQ=,tag:BuVn2D2bXgaoMXSPrppf6Q==,type:str]"
      - "ENC[AES256_GCM,data:hKzqgpU1is8KK+64euZJmI8=,iv:ozCwVc7rV0Hu+vaUTARTOahDwgc2fGPwzQ5DbS5dgGQ=,tag:zID0tx3Z9HZmMvF/mZh4Ew==,type:str]"
      - "ENC[AES256_GCM,data:orbpLTvajvIG+wqFEJYTYiAGAYPtTdwRvcGQhkc=,iv:t+uwH9QjFw0Lga2CR1kAl05PiLG5SP2qkJTBf4XbTmU=,tag:DCZDuQKj+92WZpAQcdrY2A==,type:str]"
      - "ENC[AES256_GCM,data:e3KSYDYtVYl5ZZRlnAPGI9NKnwFu1lGGcASyvANklP9IWMkWYYMEfnSZpZIAB/80,iv:eVMFeJQLxGQxple8hmHHmh7n0Pf4q+x7T/P4KlTHi+Q=,tag:Qp2T7dEpnVVk4eUq8WzxVw==,type:str]"
      - "ENC[AES256_GCM,data:454mzpVyMCA64B9PAs0WWponlKFo,iv:SrZvMiW7QIfFFmGymKmYRo8Vp42V/FJIT9Iy3/ULYU4=,tag:Xg2YgmbeDHBeJ4X6DhgD2g==,type:str]"
      - "ENC[AES256_GCM,data:EwuHnjBO0qK/O2lzRKdRMg==,iv:c0iKSj36LSd73N+aZjlNtYhPJKSzyOeONG9VUg7g7Q4=,tag:bA8ndvPYQMBbDEayQiJKXg==,type:str]"
      - "ENC[AES256_GCM,data:vrVZ/w9yj29P7k6pSz/jykc=,iv:vXiHywJjWle2qz3G4qtOi6ZA+0cKhlu+P/lNQ8+m5Do=,tag:YEQBbOsYnIVJmHQzMut/Jg==,type:str]"
      - "ENC[AES256_GCM,data:09IG87d8IEgeG6En8tWFnYfkN8usje4/BdnX822vTnOKbw==,iv:r1Zy6A/OxclZp/7Lbo8e87m+sy6vrMzvSeA5UYzugcs=,tag:3uayuo5v2JyoKKD7fStr+Q==,type:str]"
sops:
  age:
    - enc: "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySmVUdXJPdkRmbzVqRnEv\ndktDdWhwK2JkWVFqOStFM3o2VUhYRlVxL3o4CnFZaGhwSVlOWWVFV1I3OWozemh3\nc2hPRWY2ZTczK1hsU2xBeDAxVmZtWTQKLS0tIDF0Z2o1ak5RWFdTZm5aL21qcmEr\nQ0JwYWl4MFo2L1dSMldacm1jZVFqWnMKe8A93wqrTiJ6iahDBQMmPJqlP7SBFDz1\nniKU6mYa1MCeKufwchSwoJuEXq31PIOzwUPafnLwKiebDRKExrhS8A==\n-----END AGE ENCRYPTED FILE-----\n"
      recipient: "age17ggrc2pg965fvc03gfrvag95esywp9ww0tgkygpt70hf206xag5qtcwvwv"
  lastmodified: "2026-06-13T10:48:52Z"
  mac: "ENC[AES256_GCM,data:OMUMhhXt/XU5WBlGpU4PA9t9A0GCQCHJDvgBuXVzp/4Zg6rQT3nHyQ/Iqk02nsORKuLnjQ1FIv+SuDkK/2z1XMPismg67BVveYI7wpR2H6rdPjJYSsKE1+O/FO0BNT87Qwet6fagUYE9X+xgOYfOOr/d/6Ko6qOLuEk0WCwkZFg=,iv:D16OXW/+PkL18b2FbBvRI8qfODZ1ZND3B4MuPy0SSo8=,tag:lI/z6g3vEtoOAXk9h3OetQ==,type:str]"
  unencrypted_suffix: "_unencrypted"
  version: "3.13.1"
