locals {
  # Static non-mail policy RRsets remain controller-owned. Mail routing,
  # discovery, authentication, reporting, and service records are generated by
  # Stalwart from the same live service model that they advertise.
  static_zone_rrsets = {
    mta_sts_alias = {
      subname = "mta-sts"
      type    = "CNAME"
      ttl     = 3600
      rdata   = ["${local.mail_fqdn}."]
    }
    user_agent_autoconfig_alias = {
      subname = "ua-auto-config"
      type    = "CNAME"
      ttl     = 3600
      rdata   = ["${local.mail_fqdn}."]
    }
    apex_https = {
      subname = "@"
      type    = "HTTPS"
      ttl     = 86400
      rdata   = ["1 . alpn=h2"]
    }
    www_https = {
      subname = "www"
      type    = "HTTPS"
      ttl     = 86400
      rdata   = ["1 . alpn=h2"]
    }
    www_mx = {
      subname = "www"
      type    = "MX"
      ttl     = 86400
      rdata   = ["0 ."]
    }
    www_txt = {
      subname = "www"
      type    = "TXT"
      ttl     = 3600
      rdata   = ["\"v=spf1 -all\""]
    }
  }
}

resource "desec_rrset" "static_zone" {
  for_each = local.static_zone_rrsets

  domain  = local.desec_zone_name
  subname = each.value.subname
  type    = each.value.type
  ttl     = each.value.ttl
  rdata   = each.value.rdata
}
